windowrule = match:class ([cC]hrom(e|ium)|[bB]rave-browser|Microsoft-edge|Vivaldi-stable), tag +chromium-based-browser
windowrule = match:class (Firefox|zen|librewolf), tag +firefox-based-browser
windowrule = match:title (YouTube|Chaturbate), tag +video

windowrule = match:tag chromium-based-browser, tile on

windowrule = match:tag chromium-based-browser, opacity 1 0.9
windowrule = match:tag firefox-based-browser, opacity 1 0.9

windowrule = match:tag video, opacity 1.0 1.0
