# Picture-in-picture overlays
#windowrule = tag +pip, title:(Picture.{0,1}in.{0,1}[Pp]icture)
windowrule = match:tag pip, float on
windowrule = match:tag pip, pin on
windowrule = match:tag pip, size 600 338
windowrule = match:tag pip, keep_aspect_ratio on
windowrule = match:tag pip, opacity 1 1
