abbr -a -g df 'df -h'
abbr -a -g du 'du -h'
abbr -a -g mkdir 'mkdir -pv'

abbr -a -g vi 'nvim'

abbr -a -g claude-yolo 'claude --dangerously-skip-permissions'

# kubectl
abbr -a -g k 'kubectl'
abbr -a -g kgn 'kubectl get nodes'
abbr -a -g kgp 'kubectl get pods'

# docker
abbr -a -g dc 'docker compose'
abbr -a -g dcu 'docker compose up'
abbr -a -g dcud 'docker compose up -d'
abbr -a -g dcb 'docker compose up --build'
abbr -a -g dcbd 'docker compose up --build -d'
abbr -a -g dcd 'docker compose down'
abbr -a -g dcdv 'docker compose down -v'
abbr -a -g dce 'docker compose exec'
abbr -a -g dcr 'docker compose restart'
abbr -a -g dl 'docker logs'
abbr -a -g dim 'docker images'
abbr -a -g dnet 'docker network'
abbr -a -g dps 'docker ps'
abbr -a -g dpsa 'docker ps -a'
abbr -a -g dsp 'docker system prune --all'
abbr -a -g d 'docker'
abbr -a -g db 'docker build'
abbr -a -g dcl 'docker compose logs'
abbr -a -g dclf 'docker compose logs -f'
abbr -a -g dcps 'docker compose ps'
abbr -a -g dcpull 'docker compose pull'
abbr -a -g dcrm 'docker compose rm'
abbr -a -g dcstart 'docker compose start'
abbr -a -g dcstop 'docker compose stop'
abbr -a -g de 'docker exec'
abbr -a -g dei 'docker exec -i'
abbr -a -g deit 'docker exec -it'
abbr -a -g dpu 'docker pull'
abbr -a -g drm 'docker rm'
abbr -a -g drmi 'docker rmi'
abbr -a -g drun 'docker run'
abbr -a -g dst 'docker start'
abbr -a -g dstp 'docker stop'
