$color = rgba(46,52,64,1.0)
$inner_color = rgba(46,52,64,0.8)
$outer_color = rgba(216,222,233,1.0)
$font_color = rgba(216,222,233,1.0)
$check_color = rgba(136, 192, 208, 1.0)
$fail_color = rgba(200, 60, 60, 1.0)
$clock_color = rgba(220, 220, 220, 1.0)
$date_color = rgba(220, 220, 220, 0.9)

general {
    hide_cursor = true
    grace = 0
    disable_loading_bar = false
    ignore_empty_output = true
}

auth {
    fingerprint {
        enabled = true
    	ready_message = Touch the fingerprint reader
    	present_message = Scanning...
    	retry_delay = 250
    }
}

background {
    monitor =
    color = $color
    blur_passes = 2
    blur_size = 7
}

# Password input field
input-field {
    monitor =
    size = 600, 200
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.3
    dots_center = true
    outer_color = $outer_color
    inner_color = $inner_color
    font_color = $font_color
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    check_color = $check_color
    fail_color = $fail_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    position = 0, -20
    halign = center
    valign = center
}

# Clock
label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    color = $clock_color
    font_size = 90
    font_family = sans-serif
    position = 0, 260
    halign = center
    valign = center
}

# Date
label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %d %B')"
    color = $date_color
    font_size = 22
    font_family = sans-serif
    position = 0, 160
    halign = center
    valign = center
}

# Fingerprint prompt
label {
    monitor =
    text = $FPRINTPROMPT
    color = $date_color
    font_size = 16
    font_family = sans-serif
    position = 0, -150
    halign = center
    valign = center
}
